import csv
import sys
import codecs
import pprint
import keyword
import difflib
csv.field_size_limit(sys.maxsize)

tag_keys = {}

suburb_maps = {
    "ANNADALE": "ANNANDALE",
    "AMERST": "AMHERST",
 	"ANNANDALE ON HUDSON": "ANNANDALE",
 	"":"NEW YORK",
 	"21 CAMELOT LANE":"SETAUKET",
 	"APO.  AE":"NEW YORK",
 	"ARDSLEY ON HUDSON": "ARDSLEY",
 	"BAYSIDE HILLS": "BAYSIDE",
 	"BEDFORD CORNER":"BEDFORD CORNERS",
 	'BELLEROSE MANOR': 'BELLEROSE',
 	'BOLTON LNDG': 'BOLTON LANDING',
 	'BRIARCLIFF': 'BRIARCLIFF MANOR',
 	'BRIDGE LAMPTON': 'BRIDGEHAMPTON',
 	'BRIDGEHAMPTON, NY. 11932': 'BRIDGEHAMPTON',
 	'BROOKLN': 'BROOKLYN',
 	'BROOKLYN HGTS': 'BROOKLYN HEIGHTS',
 	'CAMBRIA HTS': 'CAMBRIA HEIGHTS',
 	'CASTLETON': 'SCHODACK LANDING',
	'CASTLETON ON HUDSON': 'SCHODACK LANDING',
	'CENTERPOINT': 'CENTERPORT',
	'CHERRY PLAIN': 'CHERRY VALLEY',
 	'CHESTNUT RDG': 'CHESTNUT RIDGE',
 	'CLARENCE CTR':  'CLARENCE CENTER',
 	'CLINTON CORNE': 'CLINTON CORNERS',
 	'COLLEGE': 'COLLEGE POINT',
 	'CORNWALL HDSN': 'CORNWALL',
 	'CORNWALL ON HUDSON': 'CORNWALL',
 	'CORTLANDT MANOR': 'CORTLAND',
 	'CORTLANDT MNR': 'CORTLAND',
 	'CROTON HDSN': 'CROTON FALLS',
 	'CROTON ON HUDSON': 'CROTON FALLS',
 	'CTR MORICHES': 'MORICHES',
 	'DO NOT SEND': 'NEW YORK CITY',
	'E AMHERST': 'AMHERST',
	'E GREENBUSH': 'GREENBUSH',
	'E NORTHPORT': 'NORTHPORT',
 	'E NPT': 'NORTHPORT',
 	'E PATCHOGUE': 'PATCHOGUE',
 	'E ROCHESTER': 'ROCHESTER',
 	'E. AMHERST': 'AMHERST',
 	'E. AUROLA': 'AUROLA',
 	'E. NORTHPORT': 'NORTHPORT',
 	'E.NORTHPORT': 'NORTHPORT',
 	'EAST YAPHANK': 'YAPHANK',
 	'FORESTBURGH': 'FOREST HILLS',
 	'FRANKLIN SQ': 'FRANKLIN SQUARE',
 	'GLENCOVE': 'GLEN COVE',
 	'GRANDVIEW ON HUDSON': 'GRANDVIEW',
 	'HABURG': 'HAMBURG',
 	'HASTINGS HDSN': 'HASTINGS-ON-HUDSON',
 	'HASTINGS ON H': 'HASTINGS-ON-HUDSON',
 	'HASTINGS ON HUDSON': 'HASTINGS-ON-HUDSON',
 	'HIGHLAND MLS': 'HIGHLAND MILLS',
 	'HOPEWELL': 'HOPEWELL JUNCTION',
 	'HOPEWELL JCT': 'HOPEWELL JUNCTION',
 	'HUNTINGTN STA':  'HUNTINGTON STATION',
 	'ISUMINGTON': 'NEW YORK CITY',
 	'JACKSON HTS':  'JACKSON HEIGHTS',
 	'JAMAICA ESTATES': 'JAMAICA',
 	'KENT LAKES': 'KENT LAKES',
 	'AUROLA': 'AURORA',
 	'KENT LAKES': 'KENT',
 	'LA FAYETTE': 'LAFAYETTE',
 	'LATTINGTON': 'OYSTER BAY',
 	'LEEISTON': 'LEWISTON',
 	'LEROY': 'LE ROY',
 	'LIKUD HARBOR': 'NEW YORK',
 	'LK RONKONKOMA': 'RONKONKOMA',
 	'LONG IS CITY': 'LONG ISLAND CITY',
 	'NY': 'NEW YORK',
 	'NYC': 'NEW YORK',
 	'MALDEN ON HUDSON': 'MALDEN-ON-HUDSON',
	'MARYKNOLL': 'MARYKNOLL CONVENT',
	'MC GRAW': 'MCGRAW',
	'METROPOLIS': 'METROPOLITAN CAMPS',
	'MIDDLE VLG': 'MIDDLE VILLAGE',
	'MISSISSAUGA': 'MISSISSAUGA BASIN',
	'MOREHEAD': 'HORSEHEADS',
	'MOUNT LISCO': 'MOUNT KISCO',
	'MT KISCO': 'MOUNT KISCO',
	'MT SINAI': 'MOUNT SINAI',
	'MT VERNON': 'MOUNT VERNON',
	'MT. KISCO': 'MOUNT KISCO',
	'MT. KISKO': 'MOUNT KISCO',
	'MT. SINAI': 'MOUNT SINAI',
	'N SYRACUSE': 'SYRACUSE',
	'N TONAWANDA': 'TONAWANDA',
	'N. BELLMORE': 'BELLMORE',
	'N. SALEM': 'NEW SALEM',
	'NALTA': 'MALTA',
	'NE YORK': 'NEW YORK',
	'NEW': 'NEWRYS',
	'NEW  YORK': 'NEW YORK',
	'NISKAYUDA': 'NISKAYUNA',
	'NISSEQUOQUE': 'NISSEQUOGUE',
	'NIVERVILLW': 'NIVERVILLE',
	'NORTH BALDWIN': 'NORTH HAMLIN',
	'OAKLAND GDNS': 'OAKLAND GARDENS',
	'PALM HARBOR': 'PARR HARBOR',
	'PETERSBURGH': 'PETERSBURG',
	'PLEASANT VALL': 'PLEASANT VALLEY',
	'PRT WASHINGTN': 'PORT WASHINGTON',
	'QUEENS VLG': 'QUEENS VILLAGE',
	'RCOKAWAY PARK': 'ROCKAWAY PARK',
	'REUSSELAER': 'RENSSELAER',
	'RIDGE BROOK': 'BRIDGE BROOK',
	'ROCKAWAY BCH': 'ROCKAWAY BEACH',
	'ROCKVILLE CTR': 'ROCKVILLE CENTRE',
	'ROSLYN HTS': 'ROSLYN HEIGHTS',
	'S OZONE PARK': 'OZONE PARK',
	'S RICHMOND HL': 'RICHMOND HILL',
	'SACARSDALE': 'SCARSDALE',
	'SARATOGA': 'THE SARATOGA',
	'SARATOGA SPGS': 'SARATOGA SPRINGS',
	'SHELTER IS HT': 'SHELTER ISLAND HEIGHTS',
	'SHELTER ISLAN': 'SHELTER ISLAND',
	'SO SETAUKET': 'SOUTH SETAUKET',
	'SOUTH RICHMOND HIL': 'RICHMOND HILL',
	'SOUTH RICHMOND HILL': 'RICHMOND HILL',
	'SPRNGFLD GDNS': 'SPRINGFIELD GARDENS',
	'ST JAMES': 'SAINT JAMES',
	'ST REGIS FLS': 'SAINT REGIS FALLS',
	'STATON ISLAND': 'STATEN ISLAND',
	'SUMMITT': 'SUMMIT',
	'ULSTER PARK': 'LISTER PARK',
	'UNADILLA': 'UNADILLA HOUSE',
	'UNION SPRINGS': 'LEBANON SPRINGS',
	'UNIONDALE': 'IRONDALE',
	'UPPER BROOKVILLE': 'BROOKVILLE',
	'UPPER JAY': 'TUPPER LAKE',
	'UPTON': 'FULTON',
	'UTICA': 'ATTICA',
	'VAILS GATE': 'VANDERBILT GATE',
	'VALATIE': 'GALATIA',
	'VALHALLA': 'VALHALLA FARM',
	'VALLEY COTTAGE': 'DUVAL COTTAGE',
	'VALLEY FALLS': 'ALLEN FALLS',
	'VALLEY STREAM': 'VALLEY STREAM POND',
	'VAN ETTEN': 'MAIN SETTLEMENT',
	'VARYSBURG': 'SEARSBURG',
	'VERBANK': 'RIVERBANK',
	'VERMONTVILLE': 'MONTVILLE',
	'VERNON': 'NEW VERNON',
	'VERONA': 'VERNON MALL',
	'VESTAL': 'SOUTH VESTAL',
	'VICTOR': 'VICTORY',
	'VOORHEESVILLE': 'HEDGESVILLE',
	'W AMHERST': 'AMHERST',
	'WADDINGTON': 'ARLINGTON',
	'WADING RIVER': 'SWAN RIVER',
	'WADSWORTH': 'WADSWORTH FARM',
	'WAINSCOTT': 'WAINSCOTT CHAPEL',
	'WALDEN': 'ALDEN',
	'WALKER VALLEY': 'DALE VALLEY',
	'WALLKILL': 'FALL KILL',
	'WALTER MILL': 'WALTERS HALL',
	'WALTON': 'ALTON',
	'WALWORTH': 'KENILWORTH',
	'WANTAGH': 'NORTH WANTAGH',
	'WAPPINGERS FALLS': 'HAINES FALLS',
	'WAPPINGERS FL': 'WAPPINGER TOWN HALL',
	'WARNERS': 'KARNER',
	'WARRENSBURG': 'HARRISBURG',
	'WARSAW': 'SOUTH WARSAW',
	'WASHINGTONVILLE': 'WASHINGTON HILL',
	'WASSAIC': 'CASSA',
	'WATER MILL': 'SWARTE KILL',
	'WATERFORD': 'WATERBORO',
	'WATERLOO': 'WATERBORO',
	'WATERTOWN': 'EAST WATERTOWN',
	'WATERVILLE': 'CARTERVILLE',
	'WATKINS GLEN': 'AUSTIN GLEN',
	'WAVERLY': 'EAST WAVERLY',
	'WEBSTER': 'LESTER',
	'WEEDSPORT': 'EAVESPORT',
	'WELLSBURG': 'ELLISBURG',
	'WELLSVILLE': 'OWLSVILLE',
	'WEST AMHERST': 'EAST AMHERST',
	'WEST BABYLON': 'BABYLON',
	'WEST CAMP': 'ELKS CAMP',
	'WEST CHAZY': 'WEST HALL',
	'WEST COXSACKIE': 'COXSACKIE',
	'WEST EDMESTON': 'SOUTH EDMESTON',
	'WEST FALLS': 'WEST HALL',
	'WEST HARRISON': 'HARRISON',
	'WEST HEMPSTEAD': 'SOUTH HEMPSTEAD',
	'WEST HENRIETTA': 'WEST HENRIETTA STATION',
	'WEST HURLEY': 'NEW HURLEY',
	'WEST ISLIP': 'EAST ISLIP',
	'WEST KILL': 'EAST KILL',
	'WEST MONROE': 'WETMORE',
	'WEST NYACK': 'SOUTH NYACK',
	'WEST POINT': 'ESTY POINT',
	'WEST SAND LAKE': 'EAST CANADA LAKE',
	'WEST SAYVILLE': 'WEST AMITYVILLE',
	'WEST SENECA': 'EAST SENECA',
	'WEST SHOKAN': 'WEST SHORE MARINA',
	'WEST WINFIELD': 'EAST WINFIELD',
	'WESTBROOKVILLE': 'BROOKVILLE',
	'WESTBURY': 'OLD WESTBURY',
	'WESTCHESTER': 'EASTCHESTER',
	'WESTERLO': 'LESTER FLOW',
	'WESTERNVILLE': 'STERLINGVILLE',
	'WESTFIELD': 'ENFIELD',
	'WESTFORD': 'STAMFORD',
	'WESTHAMPTON': 'EAST HAMPTON',
	'WESTMORELAND': 'MORELAND',
	'WESTPORT': 'EASTPORT',
	'WESTTOWN': 'WEST TOWER',
	'WHEATFIELD': 'HARTFIELD',
	'WHIPPLEVILLE': 'HINKLEYVILLE',
	'WHITE PLAINS': 'EAST WHITE PLAINS',
	'WHITEHALL': 'WHITE HALL',
	'WHITESBORO': 'HAILESBORO',
	'WHITESHORE': "WHITNEY'S CORNERS",
	'WHITESTONE': 'LIMESTONE',
	'WHITNEY POINT': 'CHIMNEY POINT',
	'WILLET': 'NEWVILLE',
	'WILLIAMSON': 'EAST WILLIAMSON',
	'WILLIAMSTOWN': 'WILLIAMSON TOWN HALL',
	'WILLIAMSVILLE': 'WILLIAMS HALL',
	'WILLISTON PARK': 'ELLISON PARK',
	'WILLOW': 'WILLOW LAKE',
	'WILLSBORO': 'HILLSBORO',
	'WILLSEYVILLE': 'VALLEYVILLE',
	'WILMINGTON': 'BLOOMINGTON',
	'WILSON': 'TILLSON',
	'WILTON': 'MILTON',
	'WINDHAM': 'EAST WINDHAM',
	'WINGDALE': 'IRONDALE',
	'WINTHROP': 'THROOP',
	'WOODBOURNE': 'WOODFORD',
	'WOODBURY': 'WOODBURY HALL',
	'WOODGATE': 'WOODED ESTATES',
	'WOODHAVEN': 'BROOKHAVEN',
	'WOODMERE': 'NORTH WOODMERE',
	'WOODMORE': 'WOODFORD',
	'WOODRIDGE': 'HARDWOOD RIDGE',
	'WOODSIDE': 'WOODSIDE PLAZA',
	'WOODSTOCK': 'NEW WOODSTOCK',
	'WORCESTER': 'EAST WORCESTER',
	'WURTSBORO': 'WURTSBORO HILLS',
	'WYNANTSKILL': 'CATSKILL',
	'WYOMING': 'LYCOMING',
	'YAPHANK': 'YAPHANK STATION',
	'YONKERS': 'LYKERS',
	'YORK': 'CORK',
	'YORKSHIRE': 'TAYLORSHIRE',
	'YORKTOWN HEIGHTS': 'CROWN HEIGHTS',
	'YORKTOWN HTS': 'YORK TOWN HALL',
	'YOUNGSTOWN': 'KINGSTOWN',
	'YOUNGSVILLE': 'LYONSVILLE',
	'YULAN': 'WAYLAND',
	'AUROLA': 'AURORA',
	'N.Y.': 'NEW YORK',
	'CONTBR_CITY': 'NEW YORK',
	'WACCABUC': 'NEW YORK',
	'WYKAGYL': 'NEW YORK',
	'YAPHANK': 'NEW YORK'

}


not_matched = {

 
}


def addToKeyCheck(value, cities, keys):
	if not value in cities:
		value = "_"+value
	if value in keys:
		keys[value] = keys[value] + 1
	else:
		keys[value] = 1

def update_suburb_name(suburb_name):
    suburb_name = suburb_name.upper()
    if suburb_name in suburb_maps:
        suburb_name = suburb_maps[suburb_name]
    return suburb_name


def update_city(city_name, cities):
	city_name = city_name.upper()
	if not city_name in cities:
		matches = difflib.get_close_matches(city_name, cities)
		if len(matches) > 0:
			city_name = matches[0]
	return city_name




def createCities():
	data = []
	with open("US.txt", "rb") as f:
	    reader = csv.reader(f, delimiter="\t")
	    rows = list(reader)
	    for row in rows:
			if row[10] == "NY":
				city_name = update_suburb_name(row[1])
				item = [city_name, row[4], row[5]]
				data.append(item)

	file_out = "cities.csv"
	with codecs.open(file_out, "w") as fo:
		writer = csv.writer(fo)
		writer.writerow(['city','latitude','longitude'])
		writer.writerows(data)

def getCities():
	data = []
	with open("US.txt", "rb") as f:
	    reader = csv.reader(f, delimiter="\t")
	    rows = list(reader)
	    for row in rows:
			if row[10] == "NY":
				city_name = update_suburb_name(row[1])
				data.append(city_name)
	return data

def audit(filename, cityCol, cities):
	tag_keys = {}
	with open(filename, "rU") as f:
		reader = csv.reader(f, delimiter="\t")
		rows = list(reader)
		for row in rows:
			city_name = update_suburb_name(row[cityCol])
			addToKeyCheck(city_name, cities, tag_keys)
	return tag_keys

def find_closest(city, cities):
	return difflib.get_close_matches(city, cities)[0]

def findMatches(not_found, cities):
	matched = {}
	for key in not_found:
		matches = difflib.get_close_matches(key, cities)
		if len(matches) > 0:
			matched[key[1:]] = matches[0]
	return matched


if __name__ == '__main__':
	#cities = getCities()
	#pprint.pprint(findMatches(not_matched, cities))
	#pprint.pprint(audit("P00000001-NY.txt",4, cities))
	createCities()
	
